name: multitask
channels:
  - conda-forge
  - pytorch
dependencies:
  - flake8=4.0.1
  - ipywidgets=8.1.3
  - jupyterlab=4.2.3
  - matplotlib=3.8.2
  - numpy=1.24.4
  - pip=22.0.4
  - pydantic=2.10.6
  - pylint=2.14.0
  - python=3.10.0
  - pytorch=2.6.0
  - seaborn=0.13.2
  - torchvision=0.21.0
  - tqdm=4.66.0
  - pip:
    - black==23.3.0
    - isort==5.12.0
    - statannotations==0.6.0