name: multitask
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.8.10
  - numpy=1.21.2
  - matplotlib=3.4.3
  - seaborn=0.12.0
  - jupyterlab=3.2.0
  - pytorch=1.11.0
  - torchvision=0.12.0
  - tqdm=4.56.0
  - ipywidgets=7.6.5
  - flake8=4.0.1
  - pylint=2.14.0
  - pip=22.0.4
  - pip:
    - black==23.3.0
    - isort==5.12.0
    - statannotations=0.6.0